-- All work and no play makes golu a dull boy!!. 
	-- So here is the SQL fun question for you that I prepared myself. 
	-- try to answer it: "If you are good in SQL, you can get a job in Carpentry work too!!" ..... Thinkkkkkk........